[general]
# import = ["~/.config/alacritty/alacritty-theme/themes/doom_one.toml"]
# import = ["~/.config/alacritty/alacritty-theme/themes/tokyo_night.toml"]
import = ["~/.config/alacritty/alacritty-theme/themes/carbonfox.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "AdwaitaMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "AdwaitaMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "AdwaitaMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "AdwaitaMono Nerd Font Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[window]
decorations = "None"
opacity = 0.8

[window.padding]
x = 6
y = 6

