# Set prefix to Ctrl-Space instead of Ctrl-b
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g escape-time 0

# Set scrollback buffer to 10000
set -g history-limit 10000

# Mouse scrolling
set-option -g mouse on

# Move around panels with Alt+h, j, k, l
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Status bar
set -g status-fg "#BD93F9"
set -g status-bg "#252631"
set -g status-right ""

# Split windows using / and -
unbind '"'
unbind %
bind / split-window -h
bind - split-window -v

# Resize panel
bind -n M-H resize-pane -L
bind -n M-J resize-pane -D
bind -n M-K resize-pane -U
bind -n M-L resize-pane -R

# Move panel
bind -n C-M-k swap-pane -U
bind -n C-M-j swap-pane -D

# List windows
bind-key b choose-tree -Zw
